version: '3.3'

services:
  jenkins:
    image: jenkins/jenkins:alpine
    ports:
      - 5050:8080
      - 50000:50000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - jenkins-net
      - registry-ui-net
    volumes:
      - /mnt/storage/jenkins:/var/jenkins_home

networks:
  registry-ui-net:
  jenkins-net:

volumes:
  jenkinsdata: