version: '3.3'

services:
  ui:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 5050:8080
      - 50000:50000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - jenkins-net
    volumes:
      - /mnt/storage/jenkins:/var/jenkins_home

  agent_docker:
    image: registery.exlinetr.com/jenkins-agent-docker:1.0.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - jenkins-net
    volumes:
      - /mnt/storage/jenkins:/var/jenkins_home

networks:
  jenkins-net:

volumes:
  jenkinsdata: