version: '3.7'
services:
  ui:
    image: jenkins/jenkins:lts
    user: root
    deploy:
      replicas: 1
      # placement:
      #   constraints:
      #     - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.http.routers.jenkins.service=jenkins"
        - "traefik.http.routers.jenkins.rule=Host(`jenkins.exlinetr.com`)"
        - "traefik.http.routers.jenkins.entrypoints=web"
        - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
        - "traefik.http.services.jenkins.loadbalancer.server.scheme=http"
    networks:
      - jenkins_network
      - traefik_network
    volumes:
      - /mnt/storage/jenkins:/var/jenkins_home

networks:
  traefik_network:
    external: true
  jenkins_network:
    name: jenkins_network

volumes:
  jenkins_data: